-- SynDock Phase 2 Tables: SCM + CRM Deep + WMS Deep + ERP Deep + Platform
-- Run: cat create-phase2-tables.sql | docker exec -i syndock-shop-db psql -U shop_admin -d syndock_shop

-- SCM
CREATE TABLE IF NOT EXISTS "SP_Suppliers" ("Id" SERIAL PRIMARY KEY, "TenantId" INT NOT NULL, "Name" VARCHAR(100) NOT NULL, "Code" VARCHAR(50) NOT NULL, "ContactName" VARCHAR(200), "Email" VARCHAR(200), "Phone" VARCHAR(20), "Address" VARCHAR(500), "BusinessNumber" VARCHAR(50), "Status" VARCHAR(20) DEFAULT 'Active', "Grade" VARCHAR(5) DEFAULT 'B', "LeadTimeDays" INT DEFAULT 7, "DefectRate" DECIMAL(5,2) DEFAULT 0, "OnTimeDeliveryRate" DECIMAL(5,2) DEFAULT 100, "TotalOrders" INT DEFAULT 0, "TotalAmount" DECIMAL(18,0) DEFAULT 0, "Notes" VARCHAR(500), "MetadataJson" JSONB, "CreatedBy" VARCHAR(50) NOT NULL, "CreatedAt" TIMESTAMP DEFAULT NOW(), "UpdatedBy" VARCHAR(50), "UpdatedAt" TIMESTAMP);
CREATE TABLE IF NOT EXISTS "SP_ProcurementOrders" ("Id" SERIAL PRIMARY KEY, "TenantId" INT NOT NULL, "OrderNumber" VARCHAR(50) NOT NULL, "SupplierId" INT NOT NULL, "Status" VARCHAR(20) DEFAULT 'Draft', "TotalAmount" DECIMAL(18,0) DEFAULT 0, "Currency" VARCHAR(3) DEFAULT 'KRW', "ExpectedDeliveryDate" TIMESTAMP, "ActualDeliveryDate" TIMESTAMP, "SubmittedAt" TIMESTAMP, "ConfirmedAt" TIMESTAMP, "ShippedAt" TIMESTAMP, "DeliveredAt" TIMESTAMP, "TrackingNumber" VARCHAR(50), "Notes" VARCHAR(500), "ApprovedByUserId" INT, "CreatedBy" VARCHAR(50) NOT NULL, "CreatedAt" TIMESTAMP DEFAULT NOW(), "UpdatedBy" VARCHAR(50), "UpdatedAt" TIMESTAMP);
CREATE TABLE IF NOT EXISTS "SP_ProcurementOrderItems" ("Id" SERIAL PRIMARY KEY, "TenantId" INT NOT NULL, "ProcurementOrderId" INT NOT NULL, "ProductId" INT NOT NULL, "ProductName" VARCHAR(200) DEFAULT '', "Quantity" INT DEFAULT 0, "UnitPrice" DECIMAL(18,0) DEFAULT 0, "TotalPrice" DECIMAL(18,0) DEFAULT 0, "ReceivedQuantity" INT DEFAULT 0, "LotNumber" VARCHAR(50), "CreatedBy" VARCHAR(50) NOT NULL, "CreatedAt" TIMESTAMP DEFAULT NOW(), "UpdatedBy" VARCHAR(50), "UpdatedAt" TIMESTAMP);
CREATE TABLE IF NOT EXISTS "SP_SupplierEvaluations" ("Id" SERIAL PRIMARY KEY, "TenantId" INT NOT NULL, "SupplierId" INT NOT NULL, "EvaluationPeriod" VARCHAR(10) NOT NULL, "QualityScore" INT DEFAULT 0, "DeliveryScore" INT DEFAULT 0, "PriceScore" INT DEFAULT 0, "ServiceScore" INT DEFAULT 0, "TotalScore" INT DEFAULT 0, "Grade" VARCHAR(5) DEFAULT 'B', "Comments" VARCHAR(500), "CreatedBy" VARCHAR(50) NOT NULL, "CreatedAt" TIMESTAMP DEFAULT NOW(), "UpdatedBy" VARCHAR(50), "UpdatedAt" TIMESTAMP);

-- CRM Deep
CREATE TABLE IF NOT EXISTS "SP_LeadScores" ("Id" SERIAL PRIMARY KEY, "TenantId" INT NOT NULL, "UserId" INT NOT NULL, "TotalScore" INT DEFAULT 0, "PurchaseScore" INT DEFAULT 0, "EngagementScore" INT DEFAULT 0, "RecencyScore" INT DEFAULT 0, "FrequencyScore" INT DEFAULT 0, "Grade" VARCHAR(10) DEFAULT 'C', "LastCalculatedAt" TIMESTAMP DEFAULT NOW(), "ScoreBreakdownJson" JSONB, "CreatedBy" VARCHAR(50) NOT NULL, "CreatedAt" TIMESTAMP DEFAULT NOW(), "UpdatedBy" VARCHAR(50), "UpdatedAt" TIMESTAMP);
CREATE TABLE IF NOT EXISTS "SP_VocEntries" ("Id" SERIAL PRIMARY KEY, "TenantId" INT NOT NULL, "UserId" INT, "Source" VARCHAR(20) NOT NULL, "SourceId" INT, "Content" TEXT NOT NULL, "Sentiment" VARCHAR(20) DEFAULT 'Neutral', "SentimentScore" DECIMAL(3,2) DEFAULT 0, "TopicCategory" VARCHAR(100), "Keywords" VARCHAR(200), "IsProcessed" BOOLEAN DEFAULT FALSE, "ActionTaken" VARCHAR(500), "CreatedBy" VARCHAR(50) NOT NULL, "CreatedAt" TIMESTAMP DEFAULT NOW(), "UpdatedBy" VARCHAR(50), "UpdatedAt" TIMESTAMP);
CREATE TABLE IF NOT EXISTS "SP_SalesPipelines" ("Id" SERIAL PRIMARY KEY, "TenantId" INT NOT NULL, "UserId" INT, "Title" VARCHAR(200) NOT NULL, "Stage" VARCHAR(20) DEFAULT 'Lead', "ExpectedValue" DECIMAL(18,0) DEFAULT 0, "Probability" DECIMAL(5,2) DEFAULT 0, "ExpectedCloseDate" TIMESTAMP, "AssignedTo" VARCHAR(50), "Notes" VARCHAR(500), "WonAt" TIMESTAMP, "LostAt" TIMESTAMP, "LostReason" VARCHAR(200), "CreatedBy" VARCHAR(50) NOT NULL, "CreatedAt" TIMESTAMP DEFAULT NOW(), "UpdatedBy" VARCHAR(50), "UpdatedAt" TIMESTAMP);

-- WMS Deep
CREATE TABLE IF NOT EXISTS "SP_LotTrackings" ("Id" SERIAL PRIMARY KEY, "TenantId" INT NOT NULL, "ProductId" INT NOT NULL, "LotNumber" VARCHAR(50) NOT NULL, "BatchNumber" VARCHAR(50), "ManufacturedDate" TIMESTAMP, "ExpiryDate" TIMESTAMP, "Quantity" INT DEFAULT 0, "LocationId" INT, "Status" VARCHAR(20) DEFAULT 'Available', "Notes" VARCHAR(500), "CreatedBy" VARCHAR(50) NOT NULL, "CreatedAt" TIMESTAMP DEFAULT NOW(), "UpdatedBy" VARCHAR(50), "UpdatedAt" TIMESTAMP);
CREATE TABLE IF NOT EXISTS "SP_GoodsReceipts" ("Id" SERIAL PRIMARY KEY, "TenantId" INT NOT NULL, "ReceiptNumber" VARCHAR(50) NOT NULL, "PurchaseOrderId" INT, "SupplierName" VARCHAR(100), "Status" VARCHAR(20) DEFAULT 'Pending', "ExpectedQuantity" INT DEFAULT 0, "ReceivedQuantity" INT DEFAULT 0, "AcceptedQuantity" INT DEFAULT 0, "RejectedQuantity" INT DEFAULT 0, "InspectedByUserId" INT, "InspectedAt" TIMESTAMP, "InspectionNotes" VARCHAR(500), "TargetLocationId" INT, "CreatedBy" VARCHAR(50) NOT NULL, "CreatedAt" TIMESTAMP DEFAULT NOW(), "UpdatedBy" VARCHAR(50), "UpdatedAt" TIMESTAMP);
CREATE TABLE IF NOT EXISTS "SP_GoodsReceiptItems" ("Id" SERIAL PRIMARY KEY, "TenantId" INT NOT NULL, "GoodsReceiptId" INT NOT NULL, "ProductId" INT NOT NULL, "ExpectedQuantity" INT DEFAULT 0, "ReceivedQuantity" INT DEFAULT 0, "AcceptedQuantity" INT DEFAULT 0, "RejectedQuantity" INT DEFAULT 0, "LotNumber" VARCHAR(50), "ExpiryDate" TIMESTAMP, "QualityStatus" VARCHAR(20) DEFAULT 'Pending', "Notes" VARCHAR(500), "CreatedBy" VARCHAR(50) NOT NULL, "CreatedAt" TIMESTAMP DEFAULT NOW(), "UpdatedBy" VARCHAR(50), "UpdatedAt" TIMESTAMP);
CREATE TABLE IF NOT EXISTS "SP_CycleCounts" ("Id" SERIAL PRIMARY KEY, "TenantId" INT NOT NULL, "CountNumber" VARCHAR(50) NOT NULL, "ZoneId" INT, "Status" VARCHAR(20) DEFAULT 'Planned', "CountType" VARCHAR(20) DEFAULT 'Full', "AssignedUserId" INT, "StartedAt" TIMESTAMP, "CompletedAt" TIMESTAMP, "TotalItems" INT DEFAULT 0, "CountedItems" INT DEFAULT 0, "DiscrepancyItems" INT DEFAULT 0, "AccuracyPercent" DECIMAL(5,2) DEFAULT 0, "CreatedBy" VARCHAR(50) NOT NULL, "CreatedAt" TIMESTAMP DEFAULT NOW(), "UpdatedBy" VARCHAR(50), "UpdatedAt" TIMESTAMP);
CREATE TABLE IF NOT EXISTS "SP_CycleCountItems" ("Id" SERIAL PRIMARY KEY, "TenantId" INT NOT NULL, "CycleCountId" INT NOT NULL, "ProductId" INT NOT NULL, "LocationId" INT, "SystemQuantity" INT DEFAULT 0, "CountedQuantity" INT, "Discrepancy" INT DEFAULT 0, "Status" VARCHAR(20) DEFAULT 'Pending', "CountedAt" TIMESTAMP, "Notes" VARCHAR(500), "CreatedBy" VARCHAR(50) NOT NULL, "CreatedAt" TIMESTAMP DEFAULT NOW(), "UpdatedBy" VARCHAR(50), "UpdatedAt" TIMESTAMP);

-- ERP Deep
CREATE TABLE IF NOT EXISTS "SP_AccountingPeriods" ("Id" SERIAL PRIMARY KEY, "TenantId" INT NOT NULL, "Period" VARCHAR(10) NOT NULL, "Status" VARCHAR(20) DEFAULT 'Open', "TotalDebits" DECIMAL(18,2) DEFAULT 0, "TotalCredits" DECIMAL(18,2) DEFAULT 0, "IsBalanced" BOOLEAN DEFAULT FALSE, "EntriesCount" INT DEFAULT 0, "ClosedAt" TIMESTAMP, "ClosedBy" VARCHAR(50), "CreatedBy" VARCHAR(50) NOT NULL, "CreatedAt" TIMESTAMP DEFAULT NOW(), "UpdatedBy" VARCHAR(50), "UpdatedAt" TIMESTAMP);

-- Platform
CREATE TABLE IF NOT EXISTS "SP_MigrationJobs" ("Id" SERIAL PRIMARY KEY, "TenantId" INT, "ApplicationId" INT, "SourceUrl" VARCHAR(500) NOT NULL, "SourceType" VARCHAR(20) DEFAULT 'Website', "Status" VARCHAR(20) DEFAULT 'Pending', "TotalProductsFound" INT DEFAULT 0, "TotalCategoriesFound" INT DEFAULT 0, "TotalImagesFound" INT DEFAULT 0, "ProductsImported" INT DEFAULT 0, "CategoriesImported" INT DEFAULT 0, "ImagesImported" INT DEFAULT 0, "FailedItems" INT DEFAULT 0, "ProgressPercent" DECIMAL(5,1) DEFAULT 0, "StartedAt" TIMESTAMP, "CompletedAt" TIMESTAMP, "ErrorMessage" VARCHAR(2000), "CrawlResultJson" JSONB, "ImportLogJson" JSONB, "CreatedBy" VARCHAR(50) NOT NULL, "CreatedAt" TIMESTAMP DEFAULT NOW(), "UpdatedBy" VARCHAR(50), "UpdatedAt" TIMESTAMP);
